### ISSUE TITLE
 Could not find any synthesizer weights under synthesizer/saved_models/logs-pretrained/taco_pretrained

### ISSUE THREAD

**Issue by Cm744** [datarootsio/rootslab-streamlit-demo#2]
checkpoint_state = tf.train.get_checkpoint_state(checkpoints_dir)
     40         if checkpoint_state is None:
---> 41             raise Exception("Could not find any synthesizer weights under %s" % checkpoints_dir)
     42         self.checkpoint_fpath = checkpoint_state.model_checkpoint_path
     43         if verbose:

Exception: Could not find any synthesizer weights under synthesizer/saved_models/logs-pretrained/taco_pretrained

**Comment by watsang** [comment]
you can find them [here](https://github.com/CorentinJ/Real-Time-Voice-Cloning/wiki/Pretrained-models)
